/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppCategoriesRouteImport } from './routes/_app.categories'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPurchaseReturnsRouteImport } from './routes/_app.purchase-returns'
import { Route as AppSaleReturnsRouteImport } from './routes/_app.sale-returns'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminShopsRouteImport } from './routes/admin.shops'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AppAccountsIndexRouteImport } from './routes/_app.accounts.index'
import { Route as AppAccountsIdRouteImport } from './routes/_app.accounts.$id'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppCustomersIdRouteImport } from './routes/_app.customers.$id'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppInventoryAdjustmentsRouteImport } from './routes/_app.inventory.adjustments'
import { Route as AppInventoryLowStockRouteImport } from './routes/_app.inventory.low-stock'
import { Route as AppProductsIndexRouteImport } from './routes/_app.products.index'
import { Route as AppProductsNewRouteImport } from './routes/_app.products.new'
import { Route as AppPurchasesIndexRouteImport } from './routes/_app.purchases.index'
import { Route as AppPurchasesNewRouteImport } from './routes/_app.purchases.new'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppReportsCustomersRouteImport } from './routes/_app.reports.customers'
import { Route as AppReportsExpensesRouteImport } from './routes/_app.reports.expenses'
import { Route as AppReportsProfitLossRouteImport } from './routes/_app.reports.profit-loss'
import { Route as AppReportsPurchasesRouteImport } from './routes/_app.reports.purchases'
import { Route as AppReportsSalesRouteImport } from './routes/_app.reports.sales'
import { Route as AppReportsSuppliersRouteImport } from './routes/_app.reports.suppliers'
import { Route as AppSalesIndexRouteImport } from './routes/_app.sales.index'
import { Route as AppSalesIdRouteImport } from './routes/_app.sales.$id'
import { Route as AppSettingsInvoiceRouteImport } from './routes/_app.settings.invoice'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app.settings.notifications'
import { Route as AppSettingsPrinterRouteImport } from './routes/_app.settings.printer'
import { Route as AppSettingsShopRouteImport } from './routes/_app.settings.shop'
import { Route as AppStaffIndexRouteImport } from './routes/_app.staff.index'
import { Route as AppStaffIdRouteImport } from './routes/_app.staff.$id'
import { Route as AppSuppliersIndexRouteImport } from './routes/_app.suppliers.index'
import { Route as AppSuppliersIdRouteImport } from './routes/_app.suppliers.$id'
import { Route as AdminShopsIndexRouteImport } from './routes/admin.shops.index'
import { Route as AdminShopsIdRouteImport } from './routes/admin.shops.$id'
import { Route as AppProductsIdIndexRouteImport } from './routes/_app.products.$id.index'
import { Route as AppProductsIdEditRouteImport } from './routes/_app.products.$id.edit'
import { Route as AppReportsInventoryIndexRouteImport } from './routes/_app.reports.inventory.index'
import { Route as AppReportsInventoryReportRouteImport } from './routes/_app.reports.inventory.$report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseReturnsRoute = AppPurchaseReturnsRouteImport.update({
  id: '/purchase-returns',
  path: '/purchase-returns',
  getParentRoute: () => AppRoute,
} as any)
const AppSaleReturnsRoute = AppSaleReturnsRouteImport.update({
  id: '/sale-returns',
  path: '/sale-returns',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIdRoute = AppAccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryAdjustmentsRoute = AppInventoryAdjustmentsRouteImport.update({
  id: '/inventory/adjustments',
  path: '/inventory/adjustments',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryLowStockRoute = AppInventoryLowStockRouteImport.update({
  id: '/inventory/low-stock',
  path: '/inventory/low-stock',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesIndexRoute = AppPurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesNewRoute = AppPurchasesNewRouteImport.update({
  id: '/purchases/new',
  path: '/purchases/new',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsCustomersRoute = AppReportsCustomersRouteImport.update({
  id: '/reports/customers',
  path: '/reports/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsExpensesRoute = AppReportsExpensesRouteImport.update({
  id: '/reports/expenses',
  path: '/reports/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsProfitLossRoute = AppReportsProfitLossRouteImport.update({
  id: '/reports/profit-loss',
  path: '/reports/profit-loss',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsPurchasesRoute = AppReportsPurchasesRouteImport.update({
  id: '/reports/purchases',
  path: '/reports/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsSalesRoute = AppReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsSuppliersRoute = AppReportsSuppliersRouteImport.update({
  id: '/reports/suppliers',
  path: '/reports/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIdRoute = AppSalesIdRouteImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsInvoiceRoute = AppSettingsInvoiceRouteImport.update({
  id: '/settings/invoice',
  path: '/settings/invoice',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsPrinterRoute = AppSettingsPrinterRouteImport.update({
  id: '/settings/printer',
  path: '/settings/printer',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsShopRoute = AppSettingsShopRouteImport.update({
  id: '/settings/shop',
  path: '/settings/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffIndexRoute = AppStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffIdRoute = AppStaffIdRouteImport.update({
  id: '/staff/$id',
  path: '/staff/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIndexRoute = AppSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIdRoute = AppSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AdminShopsIndexRoute = AdminShopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShopsRoute,
} as any)
const AdminShopsIdRoute = AdminShopsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminShopsRoute,
} as any)
const AppProductsIdIndexRoute = AppProductsIdIndexRouteImport.update({
  id: '/products/$id/',
  path: '/products/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIdEditRoute = AppProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsInventoryIndexRoute =
  AppReportsInventoryIndexRouteImport.update({
    id: '/reports/inventory/',
    path: '/reports/inventory/',
    getParentRoute: () => AppRoute,
  } as any)
const AppReportsInventoryReportRoute =
  AppReportsInventoryReportRouteImport.update({
    id: '/reports/inventory/$report',
    path: '/reports/inventory/$report',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/notifications': typeof AppNotificationsRoute
  '/pos': typeof AppPosRoute
  '/profile': typeof AppProfileRoute
  '/purchase-returns': typeof AppPurchaseReturnsRoute
  '/sale-returns': typeof AppSaleReturnsRoute
  '/users': typeof AppUsersRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/accounts/$id': typeof AppAccountsIdRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/inventory/adjustments': typeof AppInventoryAdjustmentsRoute
  '/inventory/low-stock': typeof AppInventoryLowStockRoute
  '/products/new': typeof AppProductsNewRoute
  '/purchases/new': typeof AppPurchasesNewRoute
  '/reports/customers': typeof AppReportsCustomersRoute
  '/reports/expenses': typeof AppReportsExpensesRoute
  '/reports/profit-loss': typeof AppReportsProfitLossRoute
  '/reports/purchases': typeof AppReportsPurchasesRoute
  '/reports/sales': typeof AppReportsSalesRoute
  '/reports/suppliers': typeof AppReportsSuppliersRoute
  '/sales/$id': typeof AppSalesIdRoute
  '/settings/invoice': typeof AppSettingsInvoiceRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/printer': typeof AppSettingsPrinterRoute
  '/settings/shop': typeof AppSettingsShopRoute
  '/staff/$id': typeof AppStaffIdRoute
  '/suppliers/$id': typeof AppSuppliersIdRoute
  '/admin/shops/$id': typeof AdminShopsIdRoute
  '/accounts/': typeof AppAccountsIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/purchases/': typeof AppPurchasesIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/sales/': typeof AppSalesIndexRoute
  '/staff/': typeof AppStaffIndexRoute
  '/suppliers/': typeof AppSuppliersIndexRoute
  '/admin/shops/': typeof AdminShopsIndexRoute
  '/products/$id/edit': typeof AppProductsIdEditRoute
  '/reports/inventory/$report': typeof AppReportsInventoryReportRoute
  '/products/$id/': typeof AppProductsIdIndexRoute
  '/reports/inventory/': typeof AppReportsInventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/notifications': typeof AppNotificationsRoute
  '/pos': typeof AppPosRoute
  '/profile': typeof AppProfileRoute
  '/purchase-returns': typeof AppPurchaseReturnsRoute
  '/sale-returns': typeof AppSaleReturnsRoute
  '/users': typeof AppUsersRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/accounts/$id': typeof AppAccountsIdRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/inventory/adjustments': typeof AppInventoryAdjustmentsRoute
  '/inventory/low-stock': typeof AppInventoryLowStockRoute
  '/products/new': typeof AppProductsNewRoute
  '/purchases/new': typeof AppPurchasesNewRoute
  '/reports/customers': typeof AppReportsCustomersRoute
  '/reports/expenses': typeof AppReportsExpensesRoute
  '/reports/profit-loss': typeof AppReportsProfitLossRoute
  '/reports/purchases': typeof AppReportsPurchasesRoute
  '/reports/sales': typeof AppReportsSalesRoute
  '/reports/suppliers': typeof AppReportsSuppliersRoute
  '/sales/$id': typeof AppSalesIdRoute
  '/settings/invoice': typeof AppSettingsInvoiceRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/printer': typeof AppSettingsPrinterRoute
  '/settings/shop': typeof AppSettingsShopRoute
  '/staff/$id': typeof AppStaffIdRoute
  '/suppliers/$id': typeof AppSuppliersIdRoute
  '/admin/shops/$id': typeof AdminShopsIdRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/purchases': typeof AppPurchasesIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/staff': typeof AppStaffIndexRoute
  '/suppliers': typeof AppSuppliersIndexRoute
  '/admin/shops': typeof AdminShopsIndexRoute
  '/products/$id/edit': typeof AppProductsIdEditRoute
  '/reports/inventory/$report': typeof AppReportsInventoryReportRoute
  '/products/$id': typeof AppProductsIdIndexRoute
  '/reports/inventory': typeof AppReportsInventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/purchase-returns': typeof AppPurchaseReturnsRoute
  '/_app/sale-returns': typeof AppSaleReturnsRoute
  '/_app/users': typeof AppUsersRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/accounts/$id': typeof AppAccountsIdRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/inventory/adjustments': typeof AppInventoryAdjustmentsRoute
  '/_app/inventory/low-stock': typeof AppInventoryLowStockRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/purchases/new': typeof AppPurchasesNewRoute
  '/_app/reports/customers': typeof AppReportsCustomersRoute
  '/_app/reports/expenses': typeof AppReportsExpensesRoute
  '/_app/reports/profit-loss': typeof AppReportsProfitLossRoute
  '/_app/reports/purchases': typeof AppReportsPurchasesRoute
  '/_app/reports/sales': typeof AppReportsSalesRoute
  '/_app/reports/suppliers': typeof AppReportsSuppliersRoute
  '/_app/sales/$id': typeof AppSalesIdRoute
  '/_app/settings/invoice': typeof AppSettingsInvoiceRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/printer': typeof AppSettingsPrinterRoute
  '/_app/settings/shop': typeof AppSettingsShopRoute
  '/_app/staff/$id': typeof AppStaffIdRoute
  '/_app/suppliers/$id': typeof AppSuppliersIdRoute
  '/admin/shops/$id': typeof AdminShopsIdRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/purchases/': typeof AppPurchasesIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/staff/': typeof AppStaffIndexRoute
  '/_app/suppliers/': typeof AppSuppliersIndexRoute
  '/admin/shops/': typeof AdminShopsIndexRoute
  '/_app/products/$id/edit': typeof AppProductsIdEditRoute
  '/_app/reports/inventory/$report': typeof AppReportsInventoryReportRoute
  '/_app/products/$id/': typeof AppProductsIdIndexRoute
  '/_app/reports/inventory/': typeof AppReportsInventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/categories'
    | '/dashboard'
    | '/expenses'
    | '/notifications'
    | '/pos'
    | '/profile'
    | '/purchase-returns'
    | '/sale-returns'
    | '/users'
    | '/admin/fees'
    | '/admin/shops'
    | '/admin/users'
    | '/admin/'
    | '/accounts/$id'
    | '/customers/$id'
    | '/inventory/adjustments'
    | '/inventory/low-stock'
    | '/products/new'
    | '/purchases/new'
    | '/reports/customers'
    | '/reports/expenses'
    | '/reports/profit-loss'
    | '/reports/purchases'
    | '/reports/sales'
    | '/reports/suppliers'
    | '/sales/$id'
    | '/settings/invoice'
    | '/settings/notifications'
    | '/settings/printer'
    | '/settings/shop'
    | '/staff/$id'
    | '/suppliers/$id'
    | '/admin/shops/$id'
    | '/accounts/'
    | '/customers/'
    | '/inventory/'
    | '/products/'
    | '/purchases/'
    | '/reports/'
    | '/sales/'
    | '/staff/'
    | '/suppliers/'
    | '/admin/shops/'
    | '/products/$id/edit'
    | '/reports/inventory/$report'
    | '/products/$id/'
    | '/reports/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/categories'
    | '/dashboard'
    | '/expenses'
    | '/notifications'
    | '/pos'
    | '/profile'
    | '/purchase-returns'
    | '/sale-returns'
    | '/users'
    | '/admin/fees'
    | '/admin/users'
    | '/admin'
    | '/accounts/$id'
    | '/customers/$id'
    | '/inventory/adjustments'
    | '/inventory/low-stock'
    | '/products/new'
    | '/purchases/new'
    | '/reports/customers'
    | '/reports/expenses'
    | '/reports/profit-loss'
    | '/reports/purchases'
    | '/reports/sales'
    | '/reports/suppliers'
    | '/sales/$id'
    | '/settings/invoice'
    | '/settings/notifications'
    | '/settings/printer'
    | '/settings/shop'
    | '/staff/$id'
    | '/suppliers/$id'
    | '/admin/shops/$id'
    | '/accounts'
    | '/customers'
    | '/inventory'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/staff'
    | '/suppliers'
    | '/admin/shops'
    | '/products/$id/edit'
    | '/reports/inventory/$report'
    | '/products/$id'
    | '/reports/inventory'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/categories'
    | '/_app/dashboard'
    | '/_app/expenses'
    | '/_app/notifications'
    | '/_app/pos'
    | '/_app/profile'
    | '/_app/purchase-returns'
    | '/_app/sale-returns'
    | '/_app/users'
    | '/admin/fees'
    | '/admin/shops'
    | '/admin/users'
    | '/admin/'
    | '/_app/accounts/$id'
    | '/_app/customers/$id'
    | '/_app/inventory/adjustments'
    | '/_app/inventory/low-stock'
    | '/_app/products/new'
    | '/_app/purchases/new'
    | '/_app/reports/customers'
    | '/_app/reports/expenses'
    | '/_app/reports/profit-loss'
    | '/_app/reports/purchases'
    | '/_app/reports/sales'
    | '/_app/reports/suppliers'
    | '/_app/sales/$id'
    | '/_app/settings/invoice'
    | '/_app/settings/notifications'
    | '/_app/settings/printer'
    | '/_app/settings/shop'
    | '/_app/staff/$id'
    | '/_app/suppliers/$id'
    | '/admin/shops/$id'
    | '/_app/accounts/'
    | '/_app/customers/'
    | '/_app/inventory/'
    | '/_app/products/'
    | '/_app/purchases/'
    | '/_app/reports/'
    | '/_app/sales/'
    | '/_app/staff/'
    | '/_app/suppliers/'
    | '/admin/shops/'
    | '/_app/products/$id/edit'
    | '/_app/reports/inventory/$report'
    | '/_app/products/$id/'
    | '/_app/reports/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-returns': {
      id: '/_app/purchase-returns'
      path: '/purchase-returns'
      fullPath: '/purchase-returns'
      preLoaderRoute: typeof AppPurchaseReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sale-returns': {
      id: '/_app/sale-returns'
      path: '/sale-returns'
      fullPath: '/sale-returns'
      preLoaderRoute: typeof AppSaleReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$id': {
      id: '/_app/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AppAccountsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/adjustments': {
      id: '/_app/inventory/adjustments'
      path: '/inventory/adjustments'
      fullPath: '/inventory/adjustments'
      preLoaderRoute: typeof AppInventoryAdjustmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/low-stock': {
      id: '/_app/inventory/low-stock'
      path: '/inventory/low-stock'
      fullPath: '/inventory/low-stock'
      preLoaderRoute: typeof AppInventoryLowStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases/': {
      id: '/_app/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AppPurchasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases/new': {
      id: '/_app/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AppPurchasesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/customers': {
      id: '/_app/reports/customers'
      path: '/reports/customers'
      fullPath: '/reports/customers'
      preLoaderRoute: typeof AppReportsCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/expenses': {
      id: '/_app/reports/expenses'
      path: '/reports/expenses'
      fullPath: '/reports/expenses'
      preLoaderRoute: typeof AppReportsExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/profit-loss': {
      id: '/_app/reports/profit-loss'
      path: '/reports/profit-loss'
      fullPath: '/reports/profit-loss'
      preLoaderRoute: typeof AppReportsProfitLossRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/purchases': {
      id: '/_app/reports/purchases'
      path: '/reports/purchases'
      fullPath: '/reports/purchases'
      preLoaderRoute: typeof AppReportsPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/sales': {
      id: '/_app/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AppReportsSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/suppliers': {
      id: '/_app/reports/suppliers'
      path: '/reports/suppliers'
      fullPath: '/reports/suppliers'
      preLoaderRoute: typeof AppReportsSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/$id': {
      id: '/_app/sales/$id'
      path: '/sales/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof AppSalesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/invoice': {
      id: '/_app/settings/invoice'
      path: '/settings/invoice'
      fullPath: '/settings/invoice'
      preLoaderRoute: typeof AppSettingsInvoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/printer': {
      id: '/_app/settings/printer'
      path: '/settings/printer'
      fullPath: '/settings/printer'
      preLoaderRoute: typeof AppSettingsPrinterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/shop': {
      id: '/_app/settings/shop'
      path: '/settings/shop'
      fullPath: '/settings/shop'
      preLoaderRoute: typeof AppSettingsShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/': {
      id: '/_app/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AppStaffIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/$id': {
      id: '/_app/staff/$id'
      path: '/staff/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof AppStaffIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/': {
      id: '/_app/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AppSuppliersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/$id': {
      id: '/_app/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof AppSuppliersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/shops/': {
      id: '/admin/shops/'
      path: '/'
      fullPath: '/admin/shops/'
      preLoaderRoute: typeof AdminShopsIndexRouteImport
      parentRoute: typeof AdminShopsRoute
    }
    '/admin/shops/$id': {
      id: '/admin/shops/$id'
      path: '/$id'
      fullPath: '/admin/shops/$id'
      preLoaderRoute: typeof AdminShopsIdRouteImport
      parentRoute: typeof AdminShopsRoute
    }
    '/_app/products/$id/': {
      id: '/_app/products/$id/'
      path: '/products/$id'
      fullPath: '/products/$id/'
      preLoaderRoute: typeof AppProductsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$id/edit': {
      id: '/_app/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof AppProductsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/inventory/': {
      id: '/_app/reports/inventory/'
      path: '/reports/inventory'
      fullPath: '/reports/inventory/'
      preLoaderRoute: typeof AppReportsInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/inventory/$report': {
      id: '/_app/reports/inventory/$report'
      path: '/reports/inventory/$report'
      fullPath: '/reports/inventory/$report'
      preLoaderRoute: typeof AppReportsInventoryReportRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPosRoute: typeof AppPosRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPurchaseReturnsRoute: typeof AppPurchaseReturnsRoute
  AppSaleReturnsRoute: typeof AppSaleReturnsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppAccountsIdRoute: typeof AppAccountsIdRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppInventoryAdjustmentsRoute: typeof AppInventoryAdjustmentsRoute
  AppInventoryLowStockRoute: typeof AppInventoryLowStockRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppPurchasesNewRoute: typeof AppPurchasesNewRoute
  AppReportsCustomersRoute: typeof AppReportsCustomersRoute
  AppReportsExpensesRoute: typeof AppReportsExpensesRoute
  AppReportsProfitLossRoute: typeof AppReportsProfitLossRoute
  AppReportsPurchasesRoute: typeof AppReportsPurchasesRoute
  AppReportsSalesRoute: typeof AppReportsSalesRoute
  AppReportsSuppliersRoute: typeof AppReportsSuppliersRoute
  AppSalesIdRoute: typeof AppSalesIdRoute
  AppSettingsInvoiceRoute: typeof AppSettingsInvoiceRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsPrinterRoute: typeof AppSettingsPrinterRoute
  AppSettingsShopRoute: typeof AppSettingsShopRoute
  AppStaffIdRoute: typeof AppStaffIdRoute
  AppSuppliersIdRoute: typeof AppSuppliersIdRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppPurchasesIndexRoute: typeof AppPurchasesIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppStaffIndexRoute: typeof AppStaffIndexRoute
  AppSuppliersIndexRoute: typeof AppSuppliersIndexRoute
  AppProductsIdEditRoute: typeof AppProductsIdEditRoute
  AppReportsInventoryReportRoute: typeof AppReportsInventoryReportRoute
  AppProductsIdIndexRoute: typeof AppProductsIdIndexRoute
  AppReportsInventoryIndexRoute: typeof AppReportsInventoryIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriesRoute: AppCategoriesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPosRoute: AppPosRoute,
  AppProfileRoute: AppProfileRoute,
  AppPurchaseReturnsRoute: AppPurchaseReturnsRoute,
  AppSaleReturnsRoute: AppSaleReturnsRoute,
  AppUsersRoute: AppUsersRoute,
  AppAccountsIdRoute: AppAccountsIdRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppInventoryAdjustmentsRoute: AppInventoryAdjustmentsRoute,
  AppInventoryLowStockRoute: AppInventoryLowStockRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppPurchasesNewRoute: AppPurchasesNewRoute,
  AppReportsCustomersRoute: AppReportsCustomersRoute,
  AppReportsExpensesRoute: AppReportsExpensesRoute,
  AppReportsProfitLossRoute: AppReportsProfitLossRoute,
  AppReportsPurchasesRoute: AppReportsPurchasesRoute,
  AppReportsSalesRoute: AppReportsSalesRoute,
  AppReportsSuppliersRoute: AppReportsSuppliersRoute,
  AppSalesIdRoute: AppSalesIdRoute,
  AppSettingsInvoiceRoute: AppSettingsInvoiceRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsPrinterRoute: AppSettingsPrinterRoute,
  AppSettingsShopRoute: AppSettingsShopRoute,
  AppStaffIdRoute: AppStaffIdRoute,
  AppSuppliersIdRoute: AppSuppliersIdRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppPurchasesIndexRoute: AppPurchasesIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppStaffIndexRoute: AppStaffIndexRoute,
  AppSuppliersIndexRoute: AppSuppliersIndexRoute,
  AppProductsIdEditRoute: AppProductsIdEditRoute,
  AppReportsInventoryReportRoute: AppReportsInventoryReportRoute,
  AppProductsIdIndexRoute: AppProductsIdIndexRoute,
  AppReportsInventoryIndexRoute: AppReportsInventoryIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminShopsRouteChildren {
  AdminShopsIdRoute: typeof AdminShopsIdRoute
  AdminShopsIndexRoute: typeof AdminShopsIndexRoute
}

const AdminShopsRouteChildren: AdminShopsRouteChildren = {
  AdminShopsIdRoute: AdminShopsIdRoute,
  AdminShopsIndexRoute: AdminShopsIndexRoute,
}

const AdminShopsRouteWithChildren = AdminShopsRoute._addFileChildren(
  AdminShopsRouteChildren,
)

interface AdminRouteChildren {
  AdminFeesRoute: typeof AdminFeesRoute
  AdminShopsRoute: typeof AdminShopsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFeesRoute: AdminFeesRoute,
  AdminShopsRoute: AdminShopsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
